-- Staging table for raw supplier delivery rows (one file load = many rows)
CREATE TABLE STG_SUPPLIER_DELIVERY (
  batch_id            VARCHAR2(50),
  performance_id      VARCHAR2(20),   -- PERF-0001, PERF-0002 etc.
  supplier_id         VARCHAR2(20),   -- SUP-009, SUP-003 etc.
  po_number           VARCHAR2(30),
  delivery_date_txt   VARCHAR2(20),
  promised_date_txt   VARCHAR2(20),
  quality_rating_txt  VARCHAR2(20),
  qty_delivered_txt   VARCHAR2(20),
  qty_rejected_txt    VARCHAR2(20),
  performance_month   VARCHAR2(10),
  load_ts             TIMESTAMP DEFAULT SYSTIMESTAMP
);


-- Basic run log
CREATE TABLE ETL_RUN_LOG (
  run_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  package_name  VARCHAR2(200),
  start_ts      TIMESTAMP,
  end_ts        TIMESTAMP,
  status        VARCHAR2(20),
  message       VARCHAR2(4000)
);

-- Row-level error log
CREATE TABLE ETL_ERROR_LOG (
  err_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  package_name  VARCHAR2(200),
  batch_id      VARCHAR2(50),
  src_file      VARCHAR2(400),
  err_stage     VARCHAR2(200),
  err_code      VARCHAR2(100),
  err_column    VARCHAR2(200),
  err_message   VARCHAR2(4000),
  logged_ts     TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Helper view to map text columns to proper types and validate
CREATE OR REPLACE VIEW VW_SUPPLIER_DELIVERY_CLEAN AS
SELECT
  supplier_id,
  po_number,
  -- Try parse dates; invalid ones become NULL so we can reject
  TO_DATE(promised_date_txt, 'YYYY-MM-DD')  AS promised_date,
  TO_DATE(delivery_date_txt, 'YYYY-MM-DD')  AS delivery_date,
  TO_NUMBER(qty_delivered_txt)              AS qty_delivered,
  TO_NUMBER(qty_rejected_txt)               AS qty_rejected,
  TO_NUMBER(quality_rating_txt)             AS quality_rating,
  -- Month key (YYYY-MM) from delivery date
  TO_CHAR(TO_DATE(delivery_date_txt,'YYYY-MM-DD'),'YYYY-MM') AS performance_month
FROM STG_SUPPLIER_DELIVERY;

SELECT * FROM ETL_RUN_LOG ORDER BY RUN_ID DESC;
SELECT * FROM ETL_ERROR_LOG;
SELECT * FROM STG_SUPPLIER_DELIVERY WHERE batch_id = 'SD_20250827182712';
SELECT * FROM SUPPLIER_PERFORMANCE WHERE performance_month = '2024-01';

SELECT * FROM STG_SUPPLIER_DELIVERY WHERE BATCH_ID = 'SD_TESTERROR';

SELECT * FROM ETL_ERROR_LOG WHERE BATCH_ID = 'SD_TESTERROR';


INSERT INTO STG_SUPPLIER_DELIVERY (
    supplier_id, po_number, delivery_date_txt, promised_date_txt,
    qty_delivered_txt, qty_rejected_txt, quality_rating_txt, batch_id
) VALUES (
    'S001', 'PO9999', 'bad-date', '2025-08-28',
    '100', '0', '5', 'SD_TESTERROR'
);


ROLLBACK;
TRUNCATE TABLE STG_SUPPLIER_DELIVERY

TRUNCATE TABLE ETL_RUN_LOG
desc stg_supplier_delivery

DROP TABLE ETL_ERROR_LOG 