-- 8. PO_LINE_ITEMS
CREATE TABLE PO_LINE_ITEMS (
    LINE_ID        VARCHAR2(20) PRIMARY KEY,
    PO_NUMBER      VARCHAR2(20) NOT NULL,
    PRODUCT_ID     VARCHAR2(20) NOT NULL,
    QUANTITY       NUMBER(10)   CHECK (QUANTITY > 0),
    UNIT_PRICE     NUMBER(12,2) CHECK (UNIT_PRICE > 0),
    LINE_TOTAL     NUMBER(14,2) GENERATED ALWAYS AS (QUANTITY * UNIT_PRICE) VIRTUAL,
    CONSTRAINT FK_PO_LINE_ORDER FOREIGN KEY (PO_NUMBER) REFERENCES PURCHASE_ORDERS(PO_NUMBER),
    CONSTRAINT FK_PO_LINE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- 9. STOCK_TRANSFERS
CREATE TABLE STOCK_TRANSFERS (
    TRANSFER_ID    VARCHAR2(20) PRIMARY KEY,
    PRODUCT_ID     VARCHAR2(20) NOT NULL,
    FROM_LOCATION  VARCHAR2(20) NOT NULL,
    TO_LOCATION    VARCHAR2(20) NOT NULL,
    QUANTITY       NUMBER(10) CHECK (QUANTITY >= 0),
    TRANSFER_DATE  DATE NOT NULL,
    STATUS         VARCHAR2(20),
    APPROVED_BY    VARCHAR2(50),
    CONSTRAINT FK_TRANSFER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_TRANSFER_FROM_LOC FOREIGN KEY (FROM_LOCATION) REFERENCES LOCATIONS(LOCATION_ID),
    CONSTRAINT FK_TRANSFER_TO_LOC FOREIGN KEY (TO_LOCATION) REFERENCES LOCATIONS(LOCATION_ID)
);

-- 10. RND_PROJECTS
CREATE TABLE RND_PROJECTS (
    PROJECT_ID        VARCHAR2(20) PRIMARY KEY,
    PROJECT_NAME      VARCHAR2(100) NOT NULL,
    PRODUCT_LINE      VARCHAR2(50),
    START_DATE        DATE NOT NULL,
    TARGET_DATE       DATE,
    BUDGET_ALLOCATED  NUMBER(14,2) CHECK (BUDGET_ALLOCATED >= 0),
    BUDGET_SPENT      NUMBER(14,2) CHECK (BUDGET_SPENT >= 0),
    PROJECT_STATUS    VARCHAR2(20) CHECK (PROJECT_STATUS IN ('PLANNED','ACTIVE','COMPLETED','ON_HOLD')),
    R_DESCRIPTION     CLOB
);

-- 11. RND_ALLOCATION
CREATE TABLE RND_ALLOCATION (
    ALLOCATION_ID   VARCHAR2(20) PRIMARY KEY,
    PROJECT_ID      VARCHAR2(20) NOT NULL,
    PRODUCT_ID      VARCHAR2(20) NOT NULL,
    ALLOCATED_QTY   NUMBER(10) CHECK (ALLOCATED_QTY > 0),
    ALLOCATION_DATE DATE NOT NULL,
    CONSUMED_QTY    NUMBER(10) CHECK (CONSUMED_QTY > 0),
    STATUS          VARCHAR2(20),
    CONSTRAINT FK_ALLOCATION_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES RND_PROJECTS(PROJECT_ID),
    CONSTRAINT FK_ALLOCATION_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- 12. AUDIT_TRAIL
CREATE TABLE AUDIT_TRAIL (
    AUDIT_ID       VARCHAR2(20) PRIMARY KEY,
    TABLE_NAME     VARCHAR2(50) NOT NULL,
    OPERATION_TYPE VARCHAR2(20) NOT NULL,
    OLD_VALUES     CLOB,
    NEW_VALUES     CLOB,
    CHANGED_BY     VARCHAR2(50),
    CHANGE_DATE    DATE DEFAULT SYSDATE
);
